function [fitresult, gof] = final_fit(Y, Z, X, plot)
%CREATEFIT(Y,Z,X)
%  Fit plane on final.dat and final.sdat
%
%  Data for 'final.dat vs. final.sdat' fit:
%      X Input : Y, first column in final.sdat
%      Y Input : Z, second column in final.sdat
%      Z Output: X, data from final.dat
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Dec-2014 16:58:09


%% Fit: 'final.dat vs. final.sdat'.
[xData, yData, zData] = prepareSurfaceData( Y, Z, X );

% Set up fittype and options.
ft = fittype( 'poly54' );

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft );

if plot == true;
  % Plot fit with data.
  figure( 'Name', 'final.dat vs. final.sdat' );
  h = plot( fitresult, [xData, yData], zData );
  legend( h, 'final.dat vs. final.sdat', 'X vs. Y, Z', 'Location', 'NorthEast' );
  % Label axes
  xlabel( 'Y' );
  ylabel( 'Z' );
  zlabel( 'X' );
  grid on
  view( -91.5, -88.0 );
end;


