function [fitresult, gof] = matlab_fits(Y, Z, X, CX, C)
%CREATEFITS(Y,Z,X,CX,C)
%  Create fits.
%
%  Data for 'Final.dat vs. Final.sdat' fit:
%      X Input : Y
%      Y Input : Z
%      Z Output: X
%  Data for 'linspace(0, 2000, 10000) vs. ty.txt' fit:
%      X Input : CX
%      Y Output: C
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Dec-2014 14:56:51

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 2, 1 );
gof = struct( 'sse', cell( 2, 1 ), ...
  'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'Final.dat vs. Final.sdat'.
[xData, yData, zData] = prepareSurfaceData( Y, Z, X );

% Set up fittype and options.
ft = fittype( 'poly34' );

% Fit model to data.
[fitresult{1}, gof(1)] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'Final.dat vs. Final.sdat' );
h = plot( fitresult{1}, [xData, yData], zData );
legend( h, 'Final.dat vs. Final.sdat', 'X vs. Y, Z', 'Location', 'NorthEast' );
% Label axes
xlabel( 'Y' );
ylabel( 'Z' );
zlabel( 'X' );
grid on
view( 179.5, -4.0 );

%% Fit: 'linspace(0, 2000, 10000) vs. ty.txt'.
[xData, yData] = prepareCurveData( CX, C );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.SmoothingParam = 0.0001;

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, opts );

% Plot residuals.
figure( 'Name', 'linspace(0, 2000, 10000) vs. ty.txt' );
h = plot( fitresult{2}, xData, yData, 'residuals' );
legend( h, 'linspace(0, 2000, 10000) vs. ty.txt - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel( 'CX' );
ylabel( 'C' );
grid on


